# Configuration file for:
#   1. FormattingSelections.R
#   2. ModelingSetupLoop.R

# Edit this file before running the analysis!
# Defaults were used in Oppenheimer et al. 2026

# FO 2026


# Project Directories ---------------------------------

# main occupancy-model project directory
#project_dir <- "/PATH/TO/YOUR/PROJECT"
project_dir <- "~/OccModWhale"

# folder containing selection CSV files
#selections_dir <- "PATH/TO/YOUR/CSV/FOLDER"
selections_dir <- "/Users/frannyoppenheimer/OccModTest/2007-2023 CSVs"

# recording metadata excel file
recordings_file <- file.path(
  project_dir,
  "Recordings.xlsx"
)

# output directory
output_dir <- file.path(
  project_dir,
  "Output"
)

# Figure directory
figure_dir <- file.path(
  project_dir,
  "Figures"
)



# Output Files ---------------------------------

# Metadata generated by Formatting_Selections.R
selections_metadata_file <- file.path(
  project_dir,
  "selections_metadata.csv"
)

# Model-selection output
aic_file <- file.path(
  output_dir,
  "aic.csv"
)

# Model coefficient output
model_coefs_file <- file.path(
  output_dir,
  "modelcoefs.csv"
)


# Create Output Directories if Needed ---------------------------------

if (!dir.exists(output_dir)) {
  dir.create(output_dir, recursive = TRUE)
}

if (!dir.exists(figure_dir)) {
  dir.create(figure_dir, recursive = TRUE)
}


# Recording Metadata Settings ---------------------------------


# Columns expected in Recordings.xlsx
recording_col_types <- c(
  "text",      # FileName
  "date",      # Date
  "numeric",   # StartTime
  "numeric",   # Duration_sec
  "numeric",   # additional variable
  "numeric",   # additional variable
  "numeric",   # additional variable
  "numeric",   # additional variable
  "numeric",   # additional variable
  "numeric"    # additional variable
)


# Period Definitions ---------------------------------

period_years <- list(
  Period1 = c(2007, 2008, 2009),
  Period2 = c(2013, 2014, 2015),
  Period3 = c(2017, 2018, 2019),
  Period4 = c(2023)
)


# Survey Settings ---------------------------------

# Number of recordings
num_recordings <- 17

# Number of surveys per recording
num_surveys <- 2

# Survey Covariates ---------------------------------
surv_covariates <- c(
  "Date",
  "Duration",
  "SST",
  "Year",
  "DOY",
  "RecordingNumber",
  "Period"
)


# Survey Covariate Transformations ---------------------------------
# Set to TRUE/FALSE depending on desired transformations.

transform_SST <- TRUE
SST_divisor <- 10

transform_DOY <- TRUE
DOY_divisor <- 100

transform_Duration <- TRUE
Duration_divisor <- 60 * 60

transform_Year <- TRUE
Year_subtract <- 2000


# Variables for modeling detection probability  ---------------------------------
# use survey to offset bias due to splitting recordings

detection_models <- c(
  "SURVEY * Period",
  "SURVEY * Period + Duration",
  "SURVEY * Period + DOY",
  "SURVEY * Period + SST"
)


# Site Covariates ---------------------------------

# Peak frequency is divided by this value.
# 1000 converts Hz to kHz.
peak_frequency_divisor <- 1000

site_covariates <- c(
  "Mean_Peak_Freq",
  "Max_Peak_Freq",
  "Min_Peak_Freq",
  "Mean_Duration_s",
  "Max_Duration_s",
  "Min_Duration_s",
  "Contour",
  "Tone_Type",
  "Harmonics"
)

# Variables for modeling occupancy probability  ---------------------------------

occupancy_models <- c(
  "Mean_Peak_Freq * Period",
  "Max_Duration_s * Period",
  "Tone_Type * Period",
  "Mean_Peak_Freq * Period + Max_Duration_s * Period",
  "Mean_Peak_Freq * Period + Tone_Type * Period",
  "Tone_Type * Period + Max_Duration_s * Period",
  "Mean_Peak_Freq * Period +
     Max_Duration_s * Period +
     Tone_Type * Period"
)


# Model Settings ---------------------------------

# RPresence occupancy model type
occupancy_model_type <- "so"

# Maximum number of function evaluations
max_function_evaluations <- 128000

# Method passed to createPao()
pao_method <- 1

# Goodness-of-fit bootstrap replicates
gof_bootstrap <- 500

# Pause between models
model_pause_seconds <- 0.5


# Model Diagnostics + Selection ---------------------------------

# Models with convergence warnings below this threshold will be removed
convergence_warning_threshold <- 3

# Whether to remove models with VC problems
remove_VC_problem_models <- TRUE

# Use AICc rather than AIC
use_AICc <- TRUE

# Cumulative model weight cutoff for models to retain
model_weight_cutoff <- 0.95


# Top Model ---------------------------------

# Set to NULL to automatically use the best-supported model from the AIC table.
# Alternatively, provide an explicit model name/formula.

top_model_override <- NULL


# Prediction Settings ---------------------------------

prediction_peak_freq <- seq(
  from = 1,
  to = 10,
  by = 1
)

prediction_max_duration <- seq(
  from = 1,
  to = 9,
  by = 1
)

